[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "mitum-general-doc"
authors = [{name = "wyuinche", email = "wyuinche.mido@gmail.com"}]
dynamic = ["version", "description"]
